[theme]

# Primary accent for interactive elements
primaryColor = '#545454'

# Background color for the main content area
backgroundColor = '#ffffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#f1f1f1'

# Color used for almost all text
textColor = '#545454'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
